import { AssignmentStatus, QuizStatus, SessionStatus, TutoringCourse } from "./tutoring-types";


const statusMap: Record<string, SessionStatus> = {
    upcoming: {
        type: 'upcoming',
        label: 'Sắp diễn ra',
        color: 'bg-blue-50 text-blue-700 border-blue-100',
    },
    completed: {
        type: 'completed',
        label: 'Đã học',
        color: 'bg-green-50 text-green-700 border-green-100',
    },
    absent: {
        type: 'absent',
        label: 'Vắng mặt',
        color: 'bg-red-50 text-red-700 border-red-100',
    },
};

const assignmentStatusMap: Record<string, AssignmentStatus> = {
    open: {
        type: 'open',
        label: 'Đang mở',
        color: 'bg-indigo-50 text-indigo-700 border-indigo-100',
    },
    notSubmitted: {
        type: 'not-submitted',
        label: 'Chưa nộp',
        color: 'bg-amber-50 text-amber-700 border-amber-100',
    },
    overdue: {
        type: 'overdue',
        label: 'Quá hạn',
        color: 'bg-red-50 text-red-700 border-red-100',
    },
    submitted: {
        type: 'submitted',
        label: 'Đã nộp',
        color: 'bg-green-50 text-green-700 border-green-100',
    },
};

const quizStatusMap: Record<string, QuizStatus> = {
    open: {
        type: 'open',
        label: 'Đang mở',
        color: 'bg-indigo-50 text-indigo-700 border-indigo-100',
    },
    notOpen: {
        type: 'not-open',
        label: 'Chưa mở',
        color: 'bg-slate-50 text-slate-700 border-slate-200',
    },
    submitted: {
        type: 'submitted',
        label: 'Đã nộp',
        color: 'bg-green-50 text-green-700 border-green-100',
    },
};

export const mockTutoringCourse: TutoringCourse = {
    id: '1',
    title: 'Toán 12 - Luyện thi Đại học',
    tutorName: 'Thầy Minh',
    tutorAvatar:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBH9peqGLCiJLYhdZEpW6-NOhZC02Rugd9qV-gL4smyLy9NLnPbIGi6G5JyacY2FhBZf-8vZsDZ8s1dzzq3bLod9QmOJXDB9US9o115ep3wT2eR37ccwjjyIn2HsA5pdt-nu36xbkkegn7kGcaXyTaudnLV1Byw08TncE2EatZfcXzNxv3T7owJ7OEbHpEVCjauVHMDHtPYlX4rg3GVg8nKsxOrY8b2WqLjBXnAZ9dWlYYAI9Z7ZWmZePIkmlfvkGF7Ms438oNXJVg',
    courseImage:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBH9peqGLCiJLYhdZEpW6-NOhZC02Rugd9qV-gL4smyLy9NLnPbIGi6G5JyacY2FhBZf-8vZsDZ8s1dzzq3bLod9QmOJXDB9US9o115ep3wT2eR37ccwjjyIn2HsA5pdt-nu36xbkkegn7kGcaXyTaudnLV1Byw08TncE2EatZfcXzNxv3T7owJ7OEbHpEVCjauVHMDHtPYlX4rg3GVg8nKsxOrY8b2WqLjBXnAZ9dWlYYAI9Z7ZWmZePIkmlfvkGF7Ms438oNXJVg',
    schedule: 'Thứ 4, Thứ 6 (19:30-21:00)',
    platform: 'Google Meet',
    status: 'Đang diễn ra',
    goal: 'Mục tiêu: 8.0+',
    sessions: [
        {
            id: 's1',
            sessionNumber: 25,
            title: 'Khảo sát hàm số - Phần 3: Ứng dụng đạo hàm',
            description:
                'Giải bài tập trắc nghiệm vận dụng cao về cực trị, giá trị lớn nhất - nhỏ nhất.',
            date: '15',
            time: 'Tháng 10',
            status: statusMap.upcoming,
            meetLink: 'https://meet.google.com/abc-defg-hij',
        },
        {
            id: 's2',
            sessionNumber: 24,
            title: 'Khảo sát hàm số - Phần 2: Đồ thị hàm số',
            description: 'Cách nhận dạng đồ thị các hàm số cơ bản và biến đổi đồ thị.',
            date: '13',
            time: 'Tháng 10',
            status: statusMap.completed,
            videoLink: '#',
        },
        {
            id: 's3',
            sessionNumber: 23,
            title: 'Khảo sát hàm số - Phần 1: Sự đồng biến, nghịch biến',
            description: 'Khái niệm và phương pháp tìm khoảng đơn điệu của hàm số.',
            date: '10',
            time: 'Tháng 10',
            status: statusMap.completed,
            videoLink: '#',
        },
        {
            id: 's4',
            sessionNumber: 22,
            title: 'Ôn tập Tổng hợp Chương 1',
            description: 'Giải bài kiểm tra 1 tiết và chữa lỗi sai thường gặp.',
            date: '06',
            time: 'Tháng 10',
            status: statusMap.absent,
            videoLink: '#',
        },
    ],
    attendance: {
        percentage: 96,
        totalSessions: 25,
        attended: 24,
        absent: 1,
    },
    assignments: [
        {
            id: 'hw1',
            title: 'Trắc nghiệm nhanh: Tiệm cận',
            type: 'quiz',
            typeLabel: 'Quiz 15p',
            status: assignmentStatusMap.open,
            duration: '15 phút',
            questionCount: 10,
            description: 'Kiểm tra nhanh kiến thức về tiệm cận đứng và tiệm cận ngang',
        },
        {
            id: 'hw2',
            title: 'Trắc nghiệm Khảo sát hàm số (P1)',
            type: 'quiz',
            typeLabel: 'Bài tập',
            status: assignmentStatusMap.overdue,
            dueDate: '15/10/2023',
            dueTime: '23:59 Hôm nay',
            duration: '30 phút',
            questionCount: 20,
        },
        {
            id: 'hw3',
            title: 'Tự luận: Vẽ đồ thị và biện luận',
            type: 'essay',
            typeLabel: 'Tự luận',
            status: assignmentStatusMap.notSubmitted,
            dueDate: '17/10/2023',
            dueTime: '18:00 T5, 17/10',
            description: 'Bài tập về vẽ đồ thị hàm số và biện luận theo tham số',
        },
        {
            id: 'hw4',
            title: 'Bài tập Chương 1: Khảo sát hàm số cơ bản',
            type: 'exercise',
            typeLabel: 'Bài tập',
            status: assignmentStatusMap.submitted,
            dueDate: '10/10/2023',
            dueTime: '10/10/2023',
            score: 9.5,
            maxScore: 10,
            questionCount: 15,
        },
        {
            id: 'hw5',
            title: 'Trắc nghiệm: Tính đơn điệu của hàm số',
            type: 'quiz',
            typeLabel: 'Trắc nghiệm',
            status: assignmentStatusMap.submitted,
            dueDate: '08/10/2023',
            dueTime: '08/10/2023',
            duration: '25 phút',
            questionCount: 12,
            score: 8.0,
            maxScore: 10,
        },
    ],
    upcomingAssignments: [
        {
            id: 'hw2',
            title: 'Trắc nghiệm Khảo sát hàm số (P1)',
            type: 'quiz',
            typeLabel: 'Bài tập',
            status: assignmentStatusMap.overdue,
            dueDate: '15/10/2023',
            dueTime: '23:59 Hôm nay',
            duration: '30 phút',
            questionCount: 20,
        },
        {
            id: 'hw3',
            title: 'Tự luận: Vẽ đồ thị và biện luận',
            type: 'essay',
            typeLabel: 'Tự luận',
            status: assignmentStatusMap.notSubmitted,
            dueDate: '17/10/2023',
            dueTime: '18:00 T5, 17/10',
            description: 'Bài tập về vẽ đồ thị hàm số và biện luận theo tham số',
        },
    ],
    quizzes: [
        {
            id: 'q1',
            title: 'Trắc nghiệm nhanh: Tiệm cận',
            type: 'quiz',
            typeLabel: 'Quiz 15p',
            status: quizStatusMap.open,
            duration: '15 phút',
            questionCount: 10,
            description: 'Kiểm tra nhanh kiến thức về tiệm cận đứng và tiệm cận ngang',
        },
        {
            id: 'q2',
            title: 'Kiểm tra 1 tiết Chương 1',
            type: 'midterm',
            typeLabel: 'Giữa kỳ',
            status: quizStatusMap.notOpen,
            duration: '45 phút',
            questionCount: 30,
            scheduledDate: '24/10/2023',
            scheduledTime: '19:00',
        },
        {
            id: 'q3',
            title: 'Kiểm tra đầu vào Khóa học',
            type: 'quiz',
            typeLabel: 'Đầu vào',
            status: quizStatusMap.submitted,
            duration: '60 phút',
            questionCount: 50,
            submittedDate: '05/10/2023',
            score: 8.5,
            maxScore: 10,
        },
        {
            id: 'q4',
            title: 'Kiểm tra giữa kỳ Toán 12',
            type: 'midterm',
            typeLabel: 'Giữa kỳ',
            status: quizStatusMap.submitted,
            duration: '90 phút',
            questionCount: 40,
            submittedDate: '20/09/2023',
            score: 7.5,
            maxScore: 10,
        },
    ],
    upcomingQuizzes: [
        {
            id: 'q2',
            title: 'Kiểm tra 1 tiết Chương 1',
            type: 'midterm',
            typeLabel: 'Giữa kỳ',
            status: quizStatusMap.notOpen,
            duration: '45 phút',
            questionCount: 30,
            scheduledDate: '24/10/2023',
            scheduledTime: '19:00',
        },
        {
            id: 'q1',
            title: 'Trắc nghiệm nhanh: Tiệm cận',
            type: 'quiz',
            typeLabel: 'Quiz 15p',
            status: quizStatusMap.open,
            duration: '15 phút',
            questionCount: 10,
            description: 'Hôm nay • 20:15',
        },
    ],
    gradeStats: {
        averageScore: 8.5,
        maxScore: 10,
        completedCount: 12,
    },
    gradeTrend: [
        { label: 'Tuần 1', score: 7.0 },
        { label: 'Tuần 2', score: 8.0 },
        { label: 'Tuần 3', score: 7.5 },
        { label: 'Tuần 4', score: 8.5 },
        { label: 'Tuần 5', score: 8.0 },
        { label: 'Tuần 6', score: 9.0 },
        { label: 'Tuần 7', score: 8.5 },
        { label: 'Tuần 8', score: 9.5 },
        { label: 'Tuần 9', score: 9.8 },
    ],
    gradeItems: [
        {
            id: 'g1',
            name: 'Bài tập 1: Sự đồng biến',
            weight: 10,
            score: 8.5,
            maxScore: 10,
            feedback: 'Làm tốt, cần chú ý điều kiện xác định.',
        },
        {
            id: 'g2',
            name: 'Bài tập 2: Cực trị',
            weight: 10,
            score: 9.0,
            maxScore: 10,
            feedback: 'Rất tốt, nắm vững phương pháp.',
        },
        {
            id: 'g3',
            name: 'Kiểm tra 15p: Tiệm cận',
            weight: 15,
            score: 7.5,
            maxScore: 10,
            feedback: 'Còn nhầm lẫn giữa tiệm cận đứng và ngang.',
        },
        {
            id: 'g4',
            name: 'Kiểm tra giữa kỳ',
            weight: 30,
            score: 8.8,
            maxScore: 10,
            feedback: 'Tiến bộ rõ rệt, tiếp tục phát huy.',
        },
    ],
    documentCategories: [
        {
            type: 'pdf',
            label: 'Bài giảng PDF',
            icon: 'picture_as_pdf',
            iconColor: 'text-red-500',
            documents: [
                {
                    id: 'doc1',
                    title: 'Chương 1: Khảo sát hàm số và vẽ đồ thị',
                    type: 'pdf',
                    fileType: 'PDF',
                    fileSize: '2.4 MB',
                    previewUrl: '#',
                    downloadUrl: '#',
                },
                {
                    id: 'doc2',
                    title: 'Chương 2: Hàm số Lũy thừa, Mũ và Logarit',
                    type: 'pdf',
                    fileType: 'PDF',
                    fileSize: '3.1 MB',
                    previewUrl: '#',
                    downloadUrl: '#',
                },
            ],
        },
        {
            type: 'video',
            label: 'Video bổ trợ',
            icon: 'smart_display',
            iconColor: 'text-purple-500',
            documents: [
                {
                    id: 'vid1',
                    title: 'Chữa bài tập vận dụng cao: Cực trị hàm số',
                    type: 'video',
                    fileType: 'MP4',
                    duration: '45:20',
                    previewUrl: '#',
                },
                {
                    id: 'vid2',
                    title: 'Kỹ năng bấm máy tính CASIO giải nhanh trắc nghiệm',
                    type: 'video',
                    fileType: 'MP4',
                    duration: '32:15',
                    previewUrl: '#',
                },
            ],
        },
        {
            type: 'reference',
            label: 'Đề tham khảo',
            icon: 'quiz',
            iconColor: 'text-green-500',
            documents: [
                {
                    id: 'ref1',
                    title: 'Đề thi thử THPT Quốc gia 2023 - Đề số 1',
                    type: 'reference',
                    fileType: 'DOCX',
                    fileSize: '1.2 MB',
                    downloadUrl: '#',
                },
            ],
        },
    ],
};