import { DocumentBuilder } from '@nestjs/swagger';

export const swaggerConfig = new DocumentBuilder()
  .setTitle('Edura API')
  .setDescription('API documentation')
  .setVersion('1.0')
  .addBearerAuth()
  .addTag('Auth', 'Authentication endpoints')
  .addTag('Users', 'User management endpoints')
  .addTag('Tutors', 'Tutor discovery and profile endpoints')
  .addTag('Tutor Application', 'Tutor application workflow endpoints')
  .addTag('Health', 'Health check endpoints')
  .addTag('Grades', 'Grade management endpoints')
  .addTag('Subjects', 'Subject management endpoints')
  .addTag('Storage', 'File storage endpoints')
  .addTag('Payment', 'Payment management endpoints')
  .addTag('Payment Webhook', 'Payment provider webhook endpoints')
  .addTag('Mock Payment', 'Mock payment testing endpoints')
  .addTag('Resource', 'Resource management endpoints')
  .addTag('Schedule Availability', 'User schedule availability endpoints')
  .addTag('Recommendations', 'Recommendation endpoints')
  .build();
